version: "3"

services:
  mariadb:
    image: mariadb:10.9
    restart: always
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE

  rabitmq:
    image: rabbitmq:3.8
    restart: always
    ports:
      - "127.0.0.1:5672:5672"
    volumes:
      - rabitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
      - RABBITMQ_DEFAULT_VHOST

volumes:
  mariadb:
    driver: local
  rabitmq:
    driver: local
